# Generated by Django 5.0.6 on 2024-05-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE multiset_user (
                id SERIAL,
                PRIMARY KEY (id),
                user_token text,
                email text NOT NULL,
                password text NOT NULL
            );
            
            CREATE TABLE multiset_group (
                id SERIAL,
                PRIMARY KEY (id),
                name text NOT NULL,
                optimize_payments bool 
            );

            CREATE TABLE member (
                id SERIAL,
                PRIMARY KEY (id),
                user_id int NOT NULL REFERENCES multiset_user(id),
                group_id int NOT NULL REFERENCES multiset_group(id)
            );

            CREATE TABLE purchase (
                id SERIAL,
                PRIMARY KEY (id),
                name text,
                category text,
                group_id int NOT NULL REFERENCES multiset_group(id),
                total_cost int,
                purchaser int REFERENCES member(id)
            );

            CREATE TABLE purchase_splits (
                id SERIAL,
                PRIMARY KEY (id),
                purchase_id int NOT NULL REFERENCES purchase(id),
                amount int,
                borrower int NOT NULL REFERENCES member(id)
            );

            CREATE TABLE cumulative_debts (
                id SERIAL,
                PRIMARY KEY (id),
                amount int,
                borrower_id int NOT NULL REFERENCES member(id),
                collector_id int NOT NULL REFERENCES member(id)
            );

            CREATE TABLE settlement_history (
                id SERIAL,
                PRIMARY KEY (id),
                purchaser_id int NOT NULL REFERENCES member(id),
                amount int,
                borrower_id int NOT NULL REFERENCES member(id)
            );

            """,
            """
            DROP TABLE member;
            DROP TABLE multiset_group;
            DROP TABLE multiset_user;
            DROP TABLE purchase;
            DROP TABLE purchase_splits;
            DROP TABLE settlement_history;
            DROP TABLE cumulative_debts;
            """,
        )
    ]
