# Generated by Django 5.0.6 on 2024-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("multiset", "0001_initial_setup")]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE settlement_history
            RENAME purchaser_id TO sender_id;
            
            ALTER TABLE settlement_history
            RENAME borrower_id TO receiver_id;
            """
        )
    ]
