# Generated by Django 5.0.6 on 2024-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("multiset", "0001_initial_setup"), ("multiset", "0002_rename_settlement_history")]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE multiset_user
            ADD COLUMN first_name TEXT,
            ADD COLUMN last_name TEXT;
            """
        )
    ]
