# Generated by Django 5.0.6 on 2024-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("multiset", "0001_initial_setup"), ("multiset", "0002_rename_settlement_history"), ("multiset", "0003_add_names_to_users")]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE settlement_history
            ADD COLUMN created_at TIMESTAMP default current_timestamp;
            """
        )
    ]
