# Generated by Django 5.0.6 on 2024-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("multiset", "0001_initial_setup"), ("multiset", "0002_rename_settlement_history"), ("multiset", "0003_add_names_to_users"), ("multiset", "0004_add_timestamp_to_settlements"), ("multiset", "0005_add_fields_to_groups")]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE member
            DROP CONSTRAINT member_group_id_fkey,
            ADD CONSTRAINT member_group_id_fkey FOREIGN KEY (group_id) REFERENCES multiset_group (id) ON UPDATE CASCADE ON DELETE CASCADE;
            """
        )
    ]
