# Generated by Django 5.0.6 on 2024-06-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("multiset", "0001_initial_setup"), ("multiset", "0002_rename_settlement_history"), ("multiset", "0003_add_names_to_users"), ("multiset", "0004_add_timestamp_to_settlements"), ("multiset", "0005_add_fields_to_groups"), ("multiset", "0006_on_delete_cascade_for_members")]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE grocery_list (
                id SERIAL PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                group_id INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                FOREIGN KEY (group_id) REFERENCES multiset_group (id) ON DELETE CASCADE
            );
            
            CREATE TABLE grocery_list_item (
                id SERIAL PRIMARY KEY,
                item_name VARCHAR(255) NOT NULL,
                member_id INTEGER NOT NULL,
                quantity INTEGER NOT NULL,
                grocery_list_id INTEGER NOT NULL,
                notes VARCHAR(255),
                completed BOOLEAN DEFAULT FALSE,
                FOREIGN KEY (grocery_list_id) REFERENCES grocery_list (id) ON DELETE CASCADE,
                FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE
            );
            """
        )
    ]
